name: Release NV-DIND

on:
  workflow_dispatch:
    inputs:
      docker_version:
        description: 'Docker Version'
        required: true
        type: string
        default: 'v26.0'
      cuda_version:
        description: 'CUDA Version'
        required: true
        type: string
        default: '12.5.0'
      cuda_ubuntu_version:
        description: 'CUDA Ubuntu Version'
        required: true
        type: string
        default: '22.04'


jobs:
  release_image:
    name: Release Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Container Metadata
        id: metadata
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/nv-dind
          flavor: |
            latest=false
          tags: |
            type=raw,value=${{ inputs.docker_version }}-${{ inputs.cuda_version }}
      - name: Build and Push Container
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          build-args: |
            DOCKER_CE_VERSION=${{ inputs.docker_version }}
            CUDA_VERSION=${{ inputs.cuda_version }}
            UBUNTU_VERSION=${{ inputs.cuda_ubuntu_version }}
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max